#!/bin/bash

# ╔════════════════════════════════════════════════════════════════╗
# ║   My Diwali Crackers - Hostinger Deployment Script             ║
# ║   Version 2.0 - Complete Deployment Guide                      ║
# ╚════════════════════════════════════════════════════════════════╝

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚀 My Diwali Crackers - Hostinger Deployment           ║"
echo "║        Complete Step-by-Step Guide                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if running on macOS or Linux
OS_TYPE=$(uname -s)
if [[ "$OS_TYPE" == "Darwin" ]]; then
    OPEN_CMD="open"
elif [[ "$OS_TYPE" == "Linux" ]]; then
    OPEN_CMD="xdg-open"
else
    OPEN_CMD="explorer"  # Windows
fi

echo "📋 DEPLOYMENT CHECKLIST"
echo "======================="
echo ""
echo "Follow these 6 steps to deploy your Diwali Crackers store:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: CREATE DATABASE ON HOSTINGER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Log in to your Hostinger Control Panel"
echo "2. Click 'Databases' → 'MySQL Databases'"
echo "3. Create new database:"
echo "   Name: mydiwalicrackers_db"
echo ""
echo "4. Click 'Databases' → 'MySQL Users'"
echo "5. Create new user:"
echo "   Username: mydiwalicrackers_user"
echo "   Password: Use a STRONG 16+ character password"
echo "            Include: UPPERCASE, lowercase, numbers, special chars (!@#$%^&*)"
echo "   Example: MyDiwali2024@Secure!"
echo ""
echo "6. Assign user to database with ALL privileges"
echo ""
echo "💾 Copy these credentials - you'll need them in Step 3:"
echo "   - DB_USER: mydiwalicrackers_user"
echo "   - DB_PASS: ___________________________"
echo "   - DB_NAME: mydiwalicrackers_db"
echo ""
read -p "✅ Press ENTER when database is created..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: DOWNLOAD & PREPARE DEPLOYMENT FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 ZIP File: mydiwalicrackers-hostinger.zip"
echo ""
echo "1. Download the ZIP file"
echo "2. Extract it to a local folder (Desktop or Documents)"
echo ""
echo "After extraction, you should see:"
echo "   ├── index.html"
echo "   ├── .htaccess"
echo "   ├── admin/"
echo "   ├── api/"
echo "   ├── assets/"
echo "   └── images/"
echo ""
read -p "✅ Press ENTER when files are extracted..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: CONFIGURE DATABASE CREDENTIALS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Edit: api/config.php"
echo ""
echo "In the extracted folder:"
echo "   1. Open 'api' folder"
echo "   2. Right-click 'config.php' → Open with Text Editor"
echo "   3. Find these lines:"
echo ""
echo "      define('DB_HOST', 'localhost');"
echo "      define('DB_USER', 'mydiwalicrackers_user');"
echo "      define('DB_PASS', 'your_strong_password');"
echo "      define('DB_NAME', 'mydiwalicrackers_db');"
echo ""
echo "   4. Replace values from Step 1:"
echo "      - DB_USER: Your Hostinger MySQL username"
echo "      - DB_PASS: Your Hostinger MySQL password"
echo "      - DB_NAME: Your database name"
echo ""
echo "   5. Save file (Ctrl+S)"
echo ""
echo "💡 TIP: If password has special characters (! @ # $ %), just paste as-is"
echo ""
read -p "✅ Press ENTER when config.php is edited & saved..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: UPLOAD FILES TO HOSTINGER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 OPTION A: File Manager (Recommended for beginners)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Log in to Hostinger Control Panel"
echo "2. Click 'File Manager'"
echo "3. Navigate to 'public_html' folder"
echo "4. Click 'Upload Files' or drag-and-drop"
echo "5. Select all extracted files"
echo "6. Upload (should take 2-5 minutes)"
echo ""
echo "✅ OPTION B: FTP Client (Faster for large uploads)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Download FileZilla from: https://filezilla-project.org"
echo "2. Install and open FileZilla"
echo "3. File → Site Manager → New Site"
echo "4. Enter Hostinger FTP credentials:"
echo "   - Host: ftp.mydiwalicrackers.com (or provided by Hostinger)"
echo "   - Port: 21"
echo "   - Username: [Your FTP username]"
echo "   - Password: [Your FTP password]"
echo "5. Connect"
echo "6. Navigate to 'public_html'"
echo "7. Drag-drop extracted files"
echo "8. Wait for upload"
echo ""
echo "📌 CRITICAL: Maintain folder structure:"
echo "   public_html/"
echo "   ├── index.html"
echo "   ├── .htaccess"
echo "   ├── admin/"
echo "   ├── api/"
echo "   └── assets/"
echo ""
read -p "✅ Press ENTER when files are uploaded to Hostinger..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: IMPORT DATABASE SCHEMA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Via phpMyAdmin:"
echo ""
echo "1. Log in to Hostinger Control Panel"
echo "2. Click 'Tools' → 'phpMyAdmin'"
echo "3. Select database: mydiwalicrackers_db"
echo "4. Click 'Import' tab"
echo "5. Click 'Choose File'"
echo "6. Select 'database.sql' (if provided)"
echo "7. Click 'Import'"
echo ""
echo "💡 If database.sql not provided, contact support for schema"
echo ""
read -p "✅ Press ENTER when database is imported..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: TEST & VERIFY DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 Test these URLs (wait 2-3 minutes for DNS to propagate):"
echo ""
echo "1️⃣  Storefront:"
echo "    https://mydiwalicrackers.com"
echo "    ✓ Should load home page with products"
echo ""
echo "2️⃣  Products Page:"
echo "    https://mydiwalicrackers.com/products"
echo "    ✓ Should show product listing"
echo ""
echo "3️⃣  Checkout Page:"
echo "    https://mydiwalicrackers.com/checkout"
echo "    ✓ Should show enquiry form"
echo "    ✓ Should show 'Apply Coupon Code' box"
echo ""
echo "4️⃣  Admin Dashboard:"
echo "    https://mydiwalicrackers.com/admin"
echo "    ✓ Should load login page"
echo "    ✓ Should be able to log in"
echo ""
echo "5️⃣  API Test:"
echo "    https://mydiwalicrackers.com/api/products"
echo "    ✓ Should return JSON data (check in browser DevTools)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Issue: 'Page Not Found' (404)"
echo "✅ Fix:"
echo "   1. Clear browser cache (Ctrl+Shift+Delete)"
echo "   2. Check all .htaccess files are uploaded"
echo "   3. In Hostinger: Settings → Advanced → AllowOverride = All"
echo "   4. Test: https://mydiwalicrackers.com/api/products"
echo ""
echo "❌ Issue: 'Cannot Connect to Database'"
echo "✅ Fix:"
echo "   1. Edit api/config.php again"
echo "   2. Verify DB_USER, DB_PASS, DB_NAME are correct"
echo "   3. Test in phpMyAdmin (should connect)"
echo ""
echo "❌ Issue: 'Coupon Box Not Showing'"
echo "✅ Fix:"
echo "   1. Open browser DevTools (F12)"
echo "   2. Go to Console tab"
echo "   3. Check for JavaScript errors"
echo "   4. Verify customer-enhancements.js loads (Network tab)"
echo ""
echo "❌ Issue: 'SSL Certificate Error'"
echo "✅ Fix:"
echo "   1. Wait 24-48 hours (Let's Encrypt activation)"
echo "   2. Clear cache"
echo "   3. Try https://mydiwalicrackers.com again"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After successful deployment:"
echo ""
echo "1️⃣  Add Products via Admin"
echo "    https://mydiwalicrackers.com/admin"
echo "    → Products → Add New Product"
echo "    → Fill Name, Price, Purchased Price"
echo "    → Upload Image"
echo "    → Save"
echo ""
echo "2️⃣  Create Coupons"
echo "    https://mydiwalicrackers.com/admin"
echo "    → Coupons → Add New Coupon"
echo "    → Code: WELCOME10"
echo "    → Discount: 10%"
echo "    → Save"
echo ""
echo "3️⃣  Test Order"
echo "    https://mydiwalicrackers.com/products"
echo "    → Add product to order"
echo "    → Go to Checkout"
echo "    → Apply coupon (WELCOME10)"
echo "    → Submit enquiry"
echo ""
echo "4️⃣  Check Orders in Admin"
echo "    https://mydiwalicrackers.com/admin"
echo "    → Orders → Should see your test order"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Deployment Complete!"
echo ""
echo "📚 Documentation:"
echo "   - HOSTINGER_QUICK_SETUP.md (beginner-friendly)"
echo "   - HOSTINGER_DEPLOYMENT_GUIDE.md (detailed reference)"
echo "   - FILES_MANIFEST.md (file-by-file description)"
echo ""
echo "📞 Support:"
echo "   - Check browser console for errors (F12)"
echo "   - Review troubleshooting section above"
echo "   - Contact Hostinger support if stuck"
echo ""
echo "✨ Happy Selling! 🚀"
echo ""

